spring:
  datasource:
    url: jdbc:mysql://172.17.1.3:3306/zk_net?useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&tinyInt1isBit=false
    username: baas
    password: B1ockch@in
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      stat-view-servlet:
        login-username: zknet-admin
        login-password: zknetHzvWYDPD
  redis:
    database: 6
    host: 172.17.1.3
    port: 6379
    password: B1ockch@in@redis
    timeout: 60s
    lettuce:
      pool:
        max-active: 8
        max-wait: -1s
        max-idle: 8
        min-idle: 0
logging:
  config: classpath:log4j2-test.xml
